version: '3'

services:
  database:
    image: postgres
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: web
    command: hanami server --host 0.0.0.0
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
    ports:
      - 2300:2300
    volumes:
      - .:/usr/app/src/
    depends_on:
      - database

volumes:
  db_data:
